/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leonyue_android_starter_MainActivity */

#ifndef _Included_com_leonyue_android_starter_MainActivity
#define _Included_com_leonyue_android_starter_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leonyue_android_starter_MainActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leonyue_android_1starter_MainActivity_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
